import type { Metadata } from 'next';

import Layout from '@/components/layout';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-montserrat`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
